PE2-ScrumBoard-Poniatowski-Maximilian/Models/CreateTaskViewModel.cs
using ScrumBoardLib.Entities;
using System.ComponentModel.DataAnnotations;

namespace PE2_ScrumBoard_Poniatowski_Maximilian.Models
{
    public class CreateTaskViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please provide the task name!")]
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public int UserId { get; set; }
    }
}

PE2-ScrumBoard-Poniatowski-Maximilian/Models/CreateUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PE2_ScrumBoard_Poniatowski_Maximilian.Models
{
    public class CreateUserViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please provide your name!")]
        public string UserName { get; set; }
    }
}

PE2-ScrumBoard-Poniatowski-Maximilian/Models/ErrorViewModel.cs
using System;

namespace PE2_ScrumBoard_Poniatowski_Maximilian.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PE2-ScrumBoard-Poniatowski-Maximilian/Models/LoginViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using ScrumBoardLib.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PE2_ScrumBoard_Poniatowski_Maximilian.Models
{
    public class LoginViewModel
    {
        private readonly IUserRepository _userRepository = null;
        public LoginViewModel(IUserRepository userRepository)
        {
            _userRepository = userRepository;

            users = _userRepository.GetAll().Result.ToList().ConvertAll(u => new SelectListItem { Value = u.Id.ToString(), Text = u.UserName });
        }

        public LoginViewModel()
        {

        }

        [Required(ErrorMessage = "Please select or create a user")]
        public int? UserId { get; set; }

        private IEnumerable<SelectListItem> users = new List<SelectListItem>();
        public IEnumerable<SelectListItem> Users
        {
            get
            {
                return users;
            }
            set { users = value; }
        }

    }
}

PE2-ScrumBoard-Poniatowski-Maximilian/Models/ScrumBoardViewModel.cs
using ScrumBoardLib.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PE2_ScrumBoard_Poniatowski_Maximilian.Models
{
    public class ScrumBoardViewModel
    {
        public User User { get; set; }
        public IEnumerable<ScrumTask> Tasks { get; set; }
    }
}

PE2-ScrumBoard-Poniatowski-Maximilian/Controllers/BoardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PE2_ScrumBoard_Poniatowski_Maximilian.Models;
using ScrumBoardLib.Entities;
using ScrumBoardLib.Interfaces;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PE2_ScrumBoard_Poniatowski_Maximilian.Controllers
{
    public class BoardController : Controller
    {
        private static User user = null;
        private readonly IUserRepository _userRepository = null;
        private readonly ITaskRepository _taskRepository = null;

        public BoardController(IUserRepository userRepository, ITaskRepository taskRepository)
        {
            _userRepository = userRepository;
            _taskRepository = taskRepository;
        }

        [HttpGet]
        public async Task<IActionResult> CreateTask()
        {
            //Send to "error view" if u try to acces ...board/createtask without being loged in.
            //(This "error view" is hidden inside the Overview View and it's trigered when u try to access the Overview View without login)
            if (user != null)
            {
                return View();
            }
            return RedirectToAction("Overview");
        }

        [HttpPost]
        public async Task<IActionResult> CreateTaskPost(CreateTaskViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateTask", model);
            }
            ScrumTask newTask = new ScrumTask { Id = model.Id, StatusId = 1, TaskDescription = model.TaskDescription, TaskName = model.TaskName, UserId = user.Id };
            await _taskRepository.Create(newTask);
            return RedirectToAction("Overview");
        }

        [HttpGet]
        public async Task<IActionResult> Overview()
        {
            ScrumBoardViewModel vm = new ScrumBoardViewModel();
            vm.User = user;
            vm.Tasks = await _taskRepository.GetAll();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Users = _userRepository.GetAll().Result.ToList().ConvertAll(u => new SelectListItem { Value = u.Id.ToString(), Text = u.UserName });
                return View("~/Views/Home/Index.cshtml", model);
            }
            user = await _userRepository.GetById((int)model.UserId);
            return RedirectToAction("Overview");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            user = null;
            return RedirectToAction("Index", "Home");
        }

        
        public async Task<IActionResult> StartTask(int id)
        {
            ScrumTask target = await _taskRepository.GetById(id);
            target.StatusId = 2;
            await _taskRepository.Update(target);
            return RedirectToAction("Overview");
        }

       
        public async Task<IActionResult> FinishTask(int id)
        {
            ScrumTask target = await _taskRepository.GetById(id);
            target.StatusId = 3;
            await _taskRepository.Update(target);
            return RedirectToAction("Overview");
        }

       
        public async Task<IActionResult> DeleteTask(int id)
        {
            await _taskRepository.DeleteById(id);
            return RedirectToAction("Overview");
        }

    }
}

PE2-ScrumBoard-Poniatowski-Maximilian/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PE2_ScrumBoard_Poniatowski_Maximilian.Models;
using ScrumBoardLib.Interfaces;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PE2_ScrumBoard_Poniatowski_Maximilian.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserRepository _userRepository = null;

        public HomeController(ILogger<HomeController> logger, IUserRepository userRepository)
        {
            _logger = logger;
            _userRepository = userRepository;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            LoginViewModel vm = new LoginViewModel(_userRepository);

            return View(vm);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PE2-ScrumBoard-Poniatowski-Maximilian/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using PE2_ScrumBoard_Poniatowski_Maximilian.Models;
using ScrumBoardLib.Entities;
using ScrumBoardLib.Interfaces;
using System.Threading.Tasks;

namespace PE2_ScrumBoard_Poniatowski_Maximilian.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository = null;
        public UserController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        [HttpGet]
        public async Task<IActionResult> CreateUser()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateUserPost(CreateUserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateUser", model);
            }
            User user = new User { Id = model.Id, UserName = model.UserName };
            await _userRepository.Create(user);
            return RedirectToAction("Index", "Home");

        }
    }
}

PE2-ScrumBoard-Poniatowski-Maximilian/Views/Board/CreateTask.cshtml
@{
    ViewData["Title"] = "Create Task";
}
@model CreateTaskViewModel

<h1 class="ink display-4">Create Task</h1>
<form asp-controller="Board" asp-action="CreateTaskPost">
    <div class="form-group">
        <label asp-for="TaskName" class="labels">Task name</label>
        <input asp-for="TaskName" class="form-control" />
        <span asp-validation-for="TaskName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TaskDescription" class="labels">Task Description</label>
        <input asp-for="TaskDescription" class="form-control" />
    </div>
    <button type="submit" class="btn-primary btn">Create</button>

</form>

PE2-ScrumBoard-Poniatowski-Maximilian/Views/Board/Overview.cshtml
@{
    ViewData["Title"] = "Tasks Overview";
}

@model ScrumBoardViewModel

@*I implemented a little "view" for when u try to access .../Board/Overview without being loged in.*@
@if (@Model.User == null)
{
    
    

    <div class="jumbotron">
        <h1 class="display-4">Fatal Error!</h1>
        <hr class="my-1">
        <p class="display-3">U need to log in, before coming here!</p>
        <p></p>
        <p class="lead mt-2">
            <a class="btn btn-lg btn-warning" asp-controller="Home" asp-action="Index" role="button">Go to the login screen</a>
        </p>
    </div>
}
else
{

    <h1 class="display-4 ink">Welcome @Model.User.UserName.ToString()</h1>
    <a asp-controller="Board" asp-action="Logout">Logout</a>
    <p class="labels">Here are your tasks, have a productive day.</p>

    <table class="table mt-2">
        <thead>
            <tr>
                <th width="33%" class="h2 text-center border-white border-top-0 coltitle">OPEN (@Model.Tasks.Where(t => t.StatusId == 1 && t.UserId == Model.User.Id).Count())</th>
                <th width="33%" class="h2 text-center border-white border-top-0 border-left border-right coltitle">IN PROGRESS (@Model.Tasks.Where(t => t.StatusId == 2 && t.UserId == Model.User.Id).Count())</th>
                <th width="33%" class="h2 text-center border-white border-top-0 coltitle">DONE (@Model.Tasks.Where(t => t.StatusId == 3 && t.UserId == Model.User.Id).Count())</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @foreach (var item in Model.Tasks.Where(t => t.StatusId == 1 && t.UserId == Model.User.Id))
                    {
                        <div class="card border bodyground my-2" width="33%">
                            <div class="card-body">
                                <h5 class="card-title">@item.TaskName</h5>
                                <hr>
                                <p class="card-text">@item.TaskDescription</p>
                                <a asp-controller="Board" asp-action="StartTask" asp-route-id="@item.Id" class="btn btn-primary">Start Task</a>
                            </div>
                        </div>
                    }
                </td>
                <td>
                    @foreach (var item in Model.Tasks.Where(t => t.StatusId == 2 && t.UserId == Model.User.Id))
                    {
                        <div class="card border bodyground inprogress my-2" width="33%">
                            <div class="card-body">
                                <h5 class="card-title">@item.TaskName</h5>
                                <hr>
                                <p class="card-text">@item.TaskDescription</p>
                                <a asp-controller="Board" asp-action="FinishTask" asp-route-id="@item.Id" class="btn btn-primary">Done</a>
                            </div>
                        </div>
                    }
                </td>
                <td>
                    @foreach (var item in Model.Tasks.Where(t => t.StatusId == 3 && t.UserId == Model.User.Id))
                    {
                        <div class="card border bodyground done my-2" width="33%">
                            <div class="card-body">
                                <h5 class="card-title">@item.TaskName</h5>
                                <hr>
                                <p class="card-text">@item.TaskDescription</p>
                                <a asp-controller="Board" asp-action="DeleteTask" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                            </div>
                        </div>
                    }
                </td>

            </tr>
        </tbody>
    </table>

    <a asp-controller="Board" asp-action="CreateTask">Create Task</a>
}

PE2-ScrumBoard-Poniatowski-Maximilian/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Login Page";
}
@model LoginViewModel

<h1 class="display-4 ink">Select User</h1>
<form asp-controller="Board" asp-action="Login" method="post">
    <div class="form-group">
        <label asp-for="UserId" class="labels">User</label>
        <select asp-for="UserId" asp-items="Model.Users" class="form-control">
            <option value="" selected disabled hidden>@Html.Raw((Model.Users.Count() == 0) ? "U need to create a new user" : "Select User")</option>
        </select>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
<a asp-controller="User" asp-action="CreateUser">Not in the list ?</a>

PE2-ScrumBoard-Poniatowski-Maximilian/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ScrumBoard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3 test">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ScrumBoardTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white">
        <div class="container">
            &copy; 2022 - PE2_ScrumBoard_Poniatowski_Maximilian
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PE2-ScrumBoard-Poniatowski-Maximilian/Views/User/CreateUser.cshtml
@{
    ViewData["Title"] = "Create User";
}
@model CreateUserViewModel

    <h1 class="ink display-4">Create new user</h1>
<form asp-controller="User" asp-action="CreateUserPost" method="post">

    <div class="form-group">
        <label asp-for="UserName"  class="labels">User name</label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>